### ISSUE TITLE
v5.9.1 1.16.2: Could not pass event AsyncPlayerChatEvent to ChatControl

### ISSUE THREAD

**Issue by NotFakeAmigoOff** [kangarko/ChatControl-Free#16]
There is something from /chatcontrol reload :

12:09:02[ERROR] Could not pass event AsyncPlayerChatEvent to ChatControl v5.9.0
java.lang.NullPointerException: null
at org.mineacademy.chatcontrol.rules.ChatCeaser.parseRules(ChatCeaser.java:238) ~[?:?]
at org.mineacademy.chatcontrol.listener.ChatListener.onPlayerChat(ChatListener.java:90) ~[?:?]
at org.mineacademy.chatcontrol.listener.ChatListener.execute(ChatListener.java:32) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[server.jar:git-Paper-187]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Paper-187]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[server.jar:git-Paper-187]
at net.minecraft.server.v1_16_R2.PlayerConnection.chat(PlayerConnection.java:1821) ~[server.jar:git-Paper-187]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1736) ~[server.jar:git-Paper-187]
at net.minecraft.server.v1_16_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[server.jar:git-Paper-187]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]

**Comment by kangarko** [comment]
Sometimes reloading does this, try clean restart
