### ISSUE TITLE
Chatcontrol may bug on Spigot 1.8

### ISSUE THREAD

**Issue by thepbordin** [kangarko/ChatControl-Free#332]
**This is my log**
Its will appear when i logging in to the server
[14:39:21 ERROR]: [ChatControl] Unhandled exception number 64 occured in onPacke
tSending(PacketEvent) for ChatControl
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedChatComponent
        at com.comphenix.protocol.wrappers.Converters$3.getSpecific(Converters.j
ava:92) ~[ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.j
ava:39) ~[ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(Structu
reModifier.java:227) ~[ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifi
er.java:195) ~[ProtocolLib.jar:4.4.0-b421]
        at kangarko.chatcontrol.hooks.ProtocolLibHook$2.onPacketSending(HookMana
ger.java:453) ~[ChatControl.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendin
gListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacket
Sending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(Pack
etFilterManager.java:588) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSendi
ng(PacketFilterManager.java:564) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(P
rotocolInjector.java:338) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSendin
g(ProtocolInjector.java:298) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(
ChannelInjector.java:367) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(Chan
nelInjector.java:66) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleSchedul
ed(ChannelInjector.java:332) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageSche
duled(ChannelInjector.java:302) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnab
le(ChannelProxy.java:127) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoo
pProxy.java:95) [ProtocolLib.jar:4.4.0-b421]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140
) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.jav
a:101) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnec
tion.java:868) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendRawMessage(Craf
tPlayer.java:150) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de
3]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendMessage(CraftPl
ayer.java:157) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.broadcast(CraftServer.java
:1269) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.broadcastMessage(CraftServ
er.java:449) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:290) [spigot-1.8-R0.1-
SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at me.minebuilders.clearlag.Util.broadcast(Util.java:35) [Clearlag.jar:?
]
        at me.minebuilders.clearlag.tasks.ClearTask.run(ClearTask.java:51) [Clea
rlag.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java
:71) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:350) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-
c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:7
09) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:3
16) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:6
34) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:537) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
>

**Comment by kangarko** [comment]
Please use the correct version of ProtocolLib that works on 1.8, or an older version.

**Comment by kangarko** [comment]
Also try removing ClearLag to see if that fixed the issue.
