### ISSUE TITLE
java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by Darcion** [kangarko/ChatControl-Free#342]
Hi,

since last update i got this error on start but everything in game looks normal. i use your free version on latest spigot 1.14.3

[03:14:21] [Server thread/INFO]: [ChatControl] Enabling ChatControl v5.8.3
[03:14:21] [Server thread/WARN]: java.nio.charset.MalformedInputException: Input length = 1
[03:14:21] [Server thread/WARN]: 	at java.nio.charset.CoderResult.throwException(Unknown Source)
[03:14:21] [Server thread/WARN]: 	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
[03:14:21] [Server thread/WARN]: 	at sun.nio.cs.StreamDecoder.read(Unknown Source)
[03:14:21] [Server thread/WARN]: 	at java.io.InputStreamReader.read(Unknown Source)
[03:14:21] [Server thread/WARN]: 	at java.io.BufferedReader.fill(Unknown Source)
[03:14:21] [Server thread/WARN]: 	at java.io.BufferedReader.readLine(Unknown Source)
[03:14:21] [Server thread/WARN]: 	at java.io.BufferedReader.readLine(Unknown Source)
[03:14:21] [Server thread/WARN]: 	at java.nio.file.Files.readAllLines(Unknown Source)
[03:14:21] [Server thread/WARN]: 	at java.nio.file.Files.readAllLines(Unknown Source)
[03:14:21] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.ChatControl.scanLegacyPackages(ChatControl.java:199)
[03:14:21] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.ChatControl.onEnable(ChatControl.java:79)
[03:14:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[03:14:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[03:14:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
[03:14:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
[03:14:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
[03:14:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:439)
[03:14:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[03:14:21] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:764)
[03:14:21] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by kangarko** [comment]
Please read this and change your encoding of your files in ChatControl/ folder to UTF-8: 

https://github.com/kangarko/chatcontrol-pro/wiki/Use-Right-Encoding
