### ISSUE TITLE
Paper 1.14.3 Errors

### ISSUE THREAD

**Issue by bladbl** [kangarko/ChatControl-Free#346]
`[19:10:15 INFO]: Hooked into: Vault
[19:10:15 WARN]: java.lang.reflect.InvocationTargetException
[19:10:15 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:10:15 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:10:15 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:10:15 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[19:10:15 WARN]:        at org.mineacademy.chatcontrol.settings.ConfHelper.invokeMethods(ConfHelper.java:83)
[19:10:15 WARN]:        at org.mineacademy.chatcontrol.settings.ConfHelper.loadValues(ConfHelper.java:69)
[19:10:15 WARN]:        at org.mineacademy.chatcontrol.settings.ConfHelper.createFileAndLoad(ConfHelper.java:114)
[19:10:15 WARN]:        at org.mineacademy.chatcontrol.settings.Settings.load(Settings.java:23)
[19:10:15 WARN]:        at org.mineacademy.chatcontrol.settings.ConfHelper.loadAll(ConfHelper.java:53)
[19:10:15 WARN]:        at org.mineacademy.chatcontrol.ChatControl.onEnable(ChatControl.java:87)
[19:10:15 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:10:15 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[19:10:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[19:10:15 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
[19:10:15 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[19:10:15 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[19:10:15 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:10:15 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[19:10:15 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1837)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1645)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979)
[19:10:15 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912)
[19:10:15 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:10:15 WARN]: Caused by: java.lang.IllegalArgumentException: Malformed config value, expected double at: Chat.Formatter.Range
[19:10:15 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[19:10:15 WARN]:        at org.mineacademy.chatcontrol.settings.ConfHelper.getDouble(ConfHelper.java:155)
[19:10:15 WARN]:        at org.mineacademy.chatcontrol.settings.Settings$Chat$Formatter.init(Settings.java:135)
[19:10:15 WARN]:        ... 34 more
[19:10:15 INFO]: !----------------------------------------------!
[19:10:15 INFO]:  Error loading ChatControl, plugin is disabled!
[19:10:15 INFO]:  Running on 1.14.3-R0.1-SNAPSHOT (v1_14_R1) and Java 1.8.0_212
[19:10:15 INFO]: !----------------------------------------------!
[19:10:15 INFO]:  Error: Unable to get the error message, search above.
[19:10:15 INFO]: !----------------------------------------------!`

**Comment by kangarko** [comment]
Set Chat.Formatter.Range to a double number such as 1.0 in your settings.yml, also use pastebin.com as its hell to read that stack trace
