### ISSUE TITLE
Missing operator(s) in commands.txt

### ISSUE THREAD

**Issue by ArtelGG** [kangarko/ChatControl-Free#352]
For some reason, I am no longer able to use `dont verbose` in `commands.txt`, when I'm quite sure I was able to before. The default file does not mention not being able to use this or any others, it just says it inherits all `rules.txt`...

```
[12:12:23 WARN]: java.lang.NullPointerException: Unknown operator: 'dont verbose' in commands.txt
[12:12:23 WARN]:        at org.mineacademy.chatcontrol.rules.ChatCeaser.loadRules(ChatCeaser.java:183)
[12:12:23 WARN]:        at org.mineacademy.chatcontrol.rules.ChatCeaser.load(ChatCeaser.java:60)
[12:12:23 WARN]:        at org.mineacademy.chatcontrol.ChatControl.onReload(ChatControl.java:250)
[12:12:23 WARN]:        at org.mineacademy.chatcontrol.CommandsHandler.handleCommand(CommandsHandler.java:192)
[12:12:23 WARN]:        at org.mineacademy.chatcontrol.CommandsHandler.onCommand(CommandsHandler.java:23)
[12:12:23 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:12:23 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:12:23 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[12:12:23 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701)
[12:12:23 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:459)
[12:12:23 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:421)
[12:12:23 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074)
[12:12:23 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918)
[12:12:23 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:12:23 INFO]: [ChatControl] Reloading configuration failed, check console. The error was: Unknown operator: 'dont verbose' in commands.txt
```

**Comment by kangarko** [comment]
Hey,

you can only use the "dont verbose" operator for packet rules (packets.txt). This has been this way since the introduction of rules in 5.0.0.
