### ISSUE TITLE
soft startup error

### ISSUE THREAD

**Issue by kikelkik** [kangarko/ChatControl-Free#380]
Hey, since I updated from 8.5.3 to 8.5.4 the following error occurs on server start (ref: error.log)

```
-------------------------[13.01.2020 04:04:35]-------------------------
ChatControl 8.5.4 encountered a NoSuchMethodException
Running Paper 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_231
-------------------------------------------------------------------------
More Information: 
REGISTRY_GET_INVERSE could not find method 'b' in 'class net.minecraft.server.v1_13_R2.RegistryMaterials'
NoSuchMethodException net.minecraft.server.v1_13_R2.RegistryMaterials.b(java.lang.Object)
	 at java.lang.Class.getMethod(Class.java:1786)
	 at org.mineacademy.chatcontrol.final.nul. .Com8.<init>(SourceFile:123)
	 at org.mineacademy.chatcontrol.final.nul. .Com8.<clinit>(SourceFile:97)
	 at org.mineacademy.chatcontrol.final.nul. .cOm6.const(SourceFile:73)
	 at org.mineacademy.chatcontrol.final.nul. .LPT7.const(SourceFile:61)
	 at org.mineacademy.chatcontrol.final.nul. .lPT1.<clinit>(SourceFile:213)
	 at org.mineacademy.chatcontrol.final.nul. .CoN.private(SourceFile:281)
	 at org.mineacademy.chatcontrol.final.nul. .a.native(SourceFile:220)
	 at org.mineacademy.chatcontrol.final.nul. .lpT2.const(SourceFile:39)
	 at org.mineacademy.chatcontrol.final.nul. .a.const(SourceFile:80)
	 at org.mineacademy.chatcontrol.final.nul. .Com1.onEnable(SourceFile:253)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Wrong channel, use the other one for the pro version
