### ISSUE TITLE
Crashes when I start it.

### ISSUE THREAD

**Issue by Saalty** [kangarko/ChatControl-Free#386]
I'm one 1.7.10 and when I launch it I get 
```
[17:18:17 WARN]: java.lang.NoClassDefFoundError: com/google/gson/JsonElement
[17:18:17 WARN]:        at org.mineacademy.chatcontrol.ChatControl.onEnable(ChatControl.java:139)
[17:18:17 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[17:18:17 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[17:18:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[17:18:17 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[17:18:17 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[17:18:17 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
[17:18:17 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
[17:18:17 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
[17:18:17 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
[17:18:17 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
[17:18:17 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[17:18:17 WARN]: Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement
[17:18:17 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[17:18:17 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[17:18:17 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[17:18:17 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[17:18:17 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[17:18:17 WARN]:        ... 12 more
[17:18:17 INFO]: !----------------------------------------------!
[17:18:17 INFO]:  Error loading ChatControl, plugin is disabled!
[17:18:17 INFO]:  Running on 1.7.10-R0.1-SNAPSHOT (v1_7_R4) and Java 1.8.0_241
[17:18:17 INFO]: !----------------------------------------------!
[17:18:17 INFO]:  Error: com/google/gson/JsonElement
[17:18:17 INFO]: !----------------------------------------------!
```
please help

**Comment by Saalty** [comment]
also idk why it is java 8 my JAVA_HOME is 13

**Comment by kangarko** [comment]
Install Java 8 and BungeeChatAPI: https://www.spigotmc.org/resources/bungeechatapi.38379/

**Comment by Saalty** [comment]
you should really list that in dependancies

**Comment by kangarko** [comment]
Thanks, done
