### ISSUE TITLE
1.8.9 - ChatControl Issue

### ISSUE THREAD

**Issue by NetflixFeelings** [kangarko/ChatControl-Free#5]
I am running 1.8.9 on my server, and out of nowhere chatcontrol died. Here's my report for it:

[23:25:45] [Server thread/INFO]: [ChatControl] Enabling ChatControl v5.6.9
[23:25:45] [Server thread/INFO]: [0;36;22mHooked into[0;30;1m: [0;37;1mEssentials[m
[23:25:45] [Server thread/INFO]: [0;36;22mHooked into[0;30;1m: [0;37;1mMultiverse-Core [0;37;22m(World Alias)[m
[23:25:45] [Server thread/INFO]: [0;36;22mHooked into[0;30;1m: [0;37;1mProtocolLib [0;37;22m(Packet Features)[m
[23:25:45] [Server thread/INFO]: [0;36;22mHooked into[0;30;1m: [0;37;1mVault[m
[23:25:45] [Server thread/INFO]: [0;36;22mHooked into[0;30;1m: [0;37;1mPlaceholderAPI[m
[23:25:45] [Server thread/WARN]: java.lang.Error: Unable to hook into PlaceholderAPI
[23:25:45] [Server thread/WARN]: 	at kangarko.chatcontrol.hooks.PlaceholderAPIHook.<init>(HookManager.java:579)
[23:25:45] [Server thread/WARN]: 	at kangarko.chatcontrol.hooks.HookManager.loadDependencies(HookManager.java:107)
[23:25:45] [Server thread/WARN]: 	at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:76)
[23:25:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[23:25:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[23:25:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[23:25:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[23:25:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[23:25:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[23:25:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[23:25:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[23:25:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[23:25:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[23:25:45] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[23:25:45] [Server thread/WARN]: Caused by: java.lang.NoSuchFieldException: placeholders
[23:25:45] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[23:25:45] [Server thread/WARN]: 	at kangarko.chatcontrol.hooks.PlaceholderAPIHook.<init>(HookManager.java:573)
[23:25:45] [Server thread/WARN]: 	... 13 more
[23:25:45] [Server thread/INFO]: [0;31;22m!----------------------------------------------![m
[23:25:45] [Server thread/INFO]:  [0;31;1mError loading ChatControl, plugin is disabled![m
[23:25:45] [Server thread/INFO]:  [0;31;1mRunning on 1.8.8-R0.2-SNAPSHOT (v1_8_R3) and Java 1.8.0_265[m
[23:25:45] [Server thread/INFO]: [0;31;22m!----------------------------------------------![m
[23:25:45] [Server thread/INFO]:  [0;31;1mError: Unable to hook into PlaceholderAPI[m
[23:25:45] [Server thread/INFO]: [0;31;22m!----------------------------------------------![m
[23:25:45] [Server thread/INFO]: [ChatControl] Disabling ChatControl v5.6.9

**Comment by kangarko** [comment]
Update to ChatControl Free 5.8.9
