### ISSUE TITLE
1.16.5: Could not pass event PlayerKickEvent

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl-Free#59]
[12:57:54] [Server thread/ERROR]: Could not pass event PlayerKickEvent to ChatControl v5.9.1
java.lang.NullPointerException: Cannot invoke "String.length()" because "input" is null
	at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:211) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.event.player.PlayerKickEvent.setLeaveMessage(PlayerKickEvent.java:134) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.mineacademy.chatcontrol.listener.PlayerListener.onKick(PlayerListener.java:148) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor956.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-12]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:454) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:432) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:502) ~[patched_1.16.5.jar:git-Airplane-12]
	at com.earth2me.essentials.commands.Commandkick.run(Commandkick.java:51) ~[?:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:174) ~[?:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:766) ~[?:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:671) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:473) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:440) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1407) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-12]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[12:57:54] [Server thread/INFO]: Player Console kicked Proomp for Kicked from server..

**Comment by Proomp** [comment]
hy

**Comment by kangarko** [comment]
Use https://github.com/kangarko/ChatControl-Free/releases/tag/5.9.2
