### ISSUE TITLE
1.5.2: Cannot find class util.CraftChatMessage

### ISSUE THREAD

**Issue by KweezyCode** [kangarko/ChatControl-Free#76]
03:09:44 [SEVERE] [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
java.lang.RuntimeException: Cannot find class util.CraftChatMessage
        at com.comphenix.protocol.utility.CachedPackage.getPackageClass(CachedPackage.java:74)
        at com.comphenix.protocol.utility.MinecraftReflection.getCraftBukkitClass(MinecraftReflection.java:1754)
        at com.comphenix.protocol.utility.MinecraftReflection.getCraftChatMessage(MinecraftReflection.java:561)
        at com.comphenix.protocol.utility.MinecraftReflection.getIChatBaseComponentClass(MinecraftReflection.java:666)
        at com.comphenix.protocol.events.PacketContainer.getChatComponents(PacketContainer.java:556)
        at org.mineacademy.chatcontrol.hook.ProtocolLibHook$2.onPacketSending(HookManager.java:375)
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:597)
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:573)
        at com.comphenix.protocol.injector.spigot.SpigotPacketInjector.packetQueued(SpigotPacketInjector.java:529)
        at com.comphenix.protocol.injector.spigot.SpigotPacketInjector.packetQueued(SpigotPacketInjector.java:509)
        at com.comphenix.protocol.injector.spigot.SpigotPacketInjector$2.intercept(SpigotPacketInjector.java:222)
        at org.spigotmc.netty.PacketListener$$EnhancerByCGLIB$$6023b46b.packetQueued(<generated>)
        at org.spigotmc.netty.PacketListener.callQueued(PacketListener.java:73)
        at org.spigotmc.netty.NettyNetworkManager.queue0(NettyNetworkManager.java:192)
        at org.spigotmc.netty.NettyNetworkManager.access$000(NettyNetworkManager.java:34)
        at org.spigotmc.netty.NettyNetworkManager$3.run(NettyNetworkManager.java:182)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:353)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:365)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_5_R3.util.CraftChatMessage
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.comphenix.protocol.utility.ClassSource$1.loadClass(ClassSource.java:36)
        at com.comphenix.protocol.utility.CachedPackage.getPackageClass(CachedPackage.java:68)
        ... 21 more
03:09:44 [SEVERE] Parameters:
  net.minecraft.server.v1_5_R3.Packet3Chat@3eaad1b0[
    message=Kweezy_Play: f
    c=true
    m=<null>
    timestamp=1672013384142
    lowPriority=false
    packetID=3
  ]

>

trying to use formatter on 1.5.2

**Comment by kangarko** [comment]
Use the right version of ProtocolLib for 1.5.2, the what you use appears too new.
