### ISSUE TITLE
1.19.2: Getting No enum constant org.bukkit.GameMode.SURVİVAL Error

### ISSUE THREAD

**Issue by hasankayra04** [kangarko/ChatControl-Free#77]
Start log here:
```
[14:30:27 INFO]: [ChatControl] Enabling ChatControl v5.9.5
[14:30:27 INFO]: Hooked into: Essentials
[14:30:27 INFO]: Hooked into: ProtocolLib (Packet Features)
[14:30:27 INFO]: Hooked into: Vault
[14:30:27 INFO]: Hooked into: PlaceholderAPI
[14:30:27 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.GameMode.SURVİVAL
[14:30:27 WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:273)
[14:30:27 WARN]:        at org.bukkit.GameMode.valueOf(GameMode.java:12)
[14:30:27 WARN]:        at ChatControl-Free-5.9.5.jar//org.mineacademy.chatcontrol.rules.Rule.parseIgnoredGamemodes(Rule.java:228)
[14:30:27 WARN]:        at ChatControl-Free-5.9.5.jar//org.mineacademy.chatcontrol.rules.ChatCeaser.loadRules(ChatCeaser.java:148)
[14:30:27 WARN]:        at ChatControl-Free-5.9.5.jar//org.mineacademy.chatcontrol.rules.ChatCeaser.load(ChatCeaser.java:59)
[14:30:27 WARN]:        at ChatControl-Free-5.9.5.jar//org.mineacademy.chatcontrol.ChatControl.onEnable(ChatControl.java:93)
[14:30:27 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:30:27 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[14:30:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548)
[14:30:27 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611)
[14:30:27 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525)
[14:30:27 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[14:30:27 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427)
[14:30:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:343)
[14:30:27 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1116)
[14:30:27 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310)
[14:30:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:30:27 INFO]: !----------------------------------------------!
[14:30:27 INFO]:  Error loading ChatControl, plugin is disabled!
[14:30:27 INFO]:  Running on 1.19.2-R0.1-SNAPSHOT (v1_19_R1) and Java 17.0.2
[14:30:27 INFO]: !----------------------------------------------!
[14:30:27 INFO]:  Error: No enum constant org.bukkit.GameMode.SURVİVAL
[14:30:27 INFO]: !----------------------------------------------!
```
I think using the method to conver lower case characters to upper case ones cause this problem because Uppercase İ = Lowercase i in my systems language. 

So: İ = i and I = ı kind of deal.

**Comment by kangarko** [comment]
You have a turkish I symbol in your SURVİVAL, it needs to be SURVIVAL not SURVİVAL (you see the little dot over the I right?)

Edit your rule file and use I instead and it will fix the error.

**Comment by hasankayra04** [comment]
I didn't edit the rule file it's default like that.

**Comment by kangarko** [comment]
Then it's your system's encoding, unfortunately what I remember from people having similar issue you have to switch your systemps language to English to fix it
